sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t kitconceptdeploy .
  - docker run -d -p 8080:8080 kitconceptdeploy
  - docker ps -a

script:
  - sleep 80
  - curl http://127.0.0.1
